server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 5
      pool-name: HikariPool
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/plank?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root

mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*Mapper.xml

emSecSecurityServerUrl: http://127.0.0.1:18888/api/verifyUserInfo?
ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode: ''
      chaojiying:
        pass: ''
        softid: 0
        user: ''
plank:
  automaticTrading: true
  enableMonitor: true
  buyPlankRatioLimit: 0.07
  buyStrategyEnum: RED_THREE_SOLDIERS
  clearanceDay: 3
  deficitMovingAverage: 6
  deficitRatio: -0.05
  dragonListTime: 1652200614000
  dragonListUrl: http://datacenter-web.eastmoney.com/api/data/v1/get?callback=jQuery1123023269286711375536_1637390018591&sortColumns=BILLBOARD_NET_AMT%2CTRADE_DATE%2CSECURITY_CODE&sortTypes=-1%2C-1%2C1&pageSize=50&pageNumber=1&reportName=RPT_DAILYBILLBOARD_DETAILS&columns=SECURITY_CODE%2CSECUCODE%2CSECURITY_NAME_ABBR%2CTRADE_DATE%2CEXPLAIN%2CCLOSE_PRICE%2CCHANGE_RATE%2CBILLBOARD_NET_AMT%2CBILLBOARD_BUY_AMT%2CBILLBOARD_SELL_AMT%2CBILLBOARD_DEAL_AMT%2CACCUM_AMOUNT%2CDEAL_NET_RATIO%2CDEAL_AMOUNT_RATIO%2CTURNOVERRATE%2CFREE_MARKET_CAP%2CEXPLANATION%2CD1_CLOSE_ADJCHRATE%2CD2_CLOSE_ADJCHRATE%2CD5_CLOSE_ADJCHRATE%2CD10_CLOSE_ADJCHRATE&source=WEB&client=WEB&filter=(TRADE_DATE%3C%3D%27{time}%27)(TRADE_DATE%3E%3D%27{time}%27)
  foreignShareholdingUrl: https://datacenter-web.eastmoney.com/api/data/v1/get?callback=jQuery112308058103061778004_1665495908389&sortColumns=HOLD_MARKET_CAP&sortTypes=-1&pageSize=50&pageNumber={pageNumber}&reportName=RPT_MUTUAL_STOCK_NORTHSTA&columns=ALL&source=WEB&client=WEB&filter=(TRADE_DATE%3D%272022-10-10%27)(INTERVAL_TYPE%3D%22Y%22)
  mainFundUrl: https://push2.eastmoney.com/api/qt/clist/get?fid=f62&po=1&pz=6000&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m:0+t:6+f:!2,m:0+t:13+f:!2,m:0+t:80+f:!2,m:1+t:2+f:!2,m:1+t:23+f:!2&fields=f12,f14,f3,f62,f184,f267,f127,f268,f164,f109,f165,f174,f160,f175
  printName: false
  profitClearanceRatio: 0.04
  profitHalfRatio: 0.08
  profitQuarterRatio: 0.1
  profitUpperRatio: 0.12
  recentDayNumber: 1
  stockPriceLowerLimit: 6
  stockPriceUpperLimit: 1000
  todayFundTrendUrl: http://stock.xueqiu.com/v5/stock/capital/flow.json?symbol={code}
  xueQiuAllStockUrl: http://xueqiu.com/service/screener/screen?category=CN&exchange=sh_sz&areacode=&indcode=&order_by=symbol&order=desc&page=1&size=5000&only_count=0&current=&pct=&mc=&volume=&_=1637244021109
  xueQiuCookie: device_id=e40e3ad4aae8c6cdb009e6713d7a7989; s=bw12h1o6cr; __utmz=1.1663563770.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); bid=9ea105651fb1563867b3225ba28c0f26_l8o4y1es; __utma=1.35355797.1663563770.1668946266.1669040678.5; acw_tc=2760826c16708092150818685eec4c6d4b97c0d120516c0e2bc530ee67fed8; Hm_lvt_1db88642e346389874251b5a1eded6e3=1670166283,1670212219,1670405094,1670809220; remember=1; xq_a_token=2879263525500db763c8c0a831e3cc053ba4ad74; xqat=2879263525500db763c8c0a831e3cc053ba4ad74; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjU3MzM3MDcyNjEsImlzcyI6InVjIiwiZXhwIjoxNjczMzE4ODUzLCJjdG0iOjE2NzA4MDkyMzE2OTQsImNpZCI6ImQ5ZDBuNEFadXAifQ.q60NPC4kZIuPoBuC1DkdLbfNbRUXmqHtdE_BiPmlROyRyd4PQYZRODiNTYWgWeTj30VM83UYpm459sHWAnPeG_hT6ORjaDBk1Ep47GAHm7nWr04dQzv_H-kUaiWGG5hwZmS41XaVqyr_8KEyWH0sjrEOUCgt5u6_GjCQRvwcwrDnZd6cSDL7pFXCDHZ0VM_8OOWTB66OioovTveUYDpUiNSm6Mdxrwu91Kxtxb85qslmvWMUg7oDLb7GACM5n2dsdieNBQAAWY4lb2ltYGqsFA9dx-PWf_2ugOKON8JKjlwLzrTa0pvt7m3bxmJOb3DMw2MRjDde3f4MCkxWrC8AhQ; xq_r_token=c343e7e34822998ed86c46f59ed6b56f22c2667a; xq_is_login=1; u=5733707261; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1670809243
  xueQiuStockDetailUrl: http://stock.xueqiu.com/v5/stock/chart/kline.json?symbol={code}&begin={time}&period=day&type=before&count=-{recentDayNumber}&indicator=kline,pe,pb,ps,pcf,market_capital,agt,ggt,balance
