server:
  port: 8088
spring:
  redis:
    database: 0
    host: 47.102.117.4
    port: 6379

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 5
      pool-name: HikariPool
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.102.117.4:3307/plank?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root



logging:
  level:
    root: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
  file:
    name: plank.log



mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*Mapper.xml

emSecSecurityServerUrl: http://127.0.0.1:18888/api/verifyUserInfo?
ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode: ''
      chaojiying:
        pass: ''
        softid: 0
        user: ''
plank:
  automaticTrading: true
  enableMonitor: true
  buyPlankRatioLimit: 0.07
  buyStrategyEnum: RED_THREE_SOLDIERS
  clearanceDay: 3
  deficitMovingAverage: 6
  deficitRatio: -0.05
  dragonListTime: 1652200614000
  dragonListUrl: http://datacenter-web.eastmoney.com/api/data/v1/get?callback=jQuery1123023269286711375536_1637390018591&sortColumns=BILLBOARD_NET_AMT%2CTRADE_DATE%2CSECURITY_CODE&sortTypes=-1%2C-1%2C1&pageSize=50&pageNumber=1&reportName=RPT_DAILYBILLBOARD_DETAILS&columns=SECURITY_CODE%2CSECUCODE%2CSECURITY_NAME_ABBR%2CTRADE_DATE%2CEXPLAIN%2CCLOSE_PRICE%2CCHANGE_RATE%2CBILLBOARD_NET_AMT%2CBILLBOARD_BUY_AMT%2CBILLBOARD_SELL_AMT%2CBILLBOARD_DEAL_AMT%2CACCUM_AMOUNT%2CDEAL_NET_RATIO%2CDEAL_AMOUNT_RATIO%2CTURNOVERRATE%2CFREE_MARKET_CAP%2CEXPLANATION%2CD1_CLOSE_ADJCHRATE%2CD2_CLOSE_ADJCHRATE%2CD5_CLOSE_ADJCHRATE%2CD10_CLOSE_ADJCHRATE&source=WEB&client=WEB&filter=(TRADE_DATE%3C%3D%27{time}%27)(TRADE_DATE%3E%3D%27{time}%27)
  foreignShareholdingUrl: https://datacenter-web.eastmoney.com/api/data/v1/get?callback=jQuery112308058103061778004_1665495908389&sortColumns=HOLD_MARKET_CAP&sortTypes=-1&pageSize=50&pageNumber={pageNumber}&reportName=RPT_MUTUAL_STOCK_NORTHSTA&columns=ALL&source=WEB&client=WEB&filter=(TRADE_DATE%3D%272022-10-10%27)(INTERVAL_TYPE%3D%22Y%22)
  mainFundUrl: https://push2.eastmoney.com/api/qt/clist/get?fid=f62&po=1&pz=6000&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m:0+t:6+f:!2,m:0+t:13+f:!2,m:0+t:80+f:!2,m:1+t:2+f:!2,m:1+t:23+f:!2&fields=f12,f14,f3,f62,f184,f267,f127,f268,f164,f109,f165,f174,f160,f175
  printName: false
  profitClearanceRatio: 0.04
  profitHalfRatio: 0.08
  profitQuarterRatio: 0.1
  profitUpperRatio: 0.12
  recentDayNumber: 200
  stockPriceLowerLimit: 6
  stockPriceUpperLimit: 1000
  todayFundTrendUrl: http://stock.xueqiu.com/v5/stock/capital/flow.json?symbol={code}
  xueQiuAllStockUrl: http://xueqiu.com/service/screener/screen?category=CN&exchange=sh_sz&areacode=&indcode=&order_by=symbol&order=desc&page=1&size=5000&only_count=0&current=&pct=&mc=&volume=&_=1637244021109
  xueQiuCookie: device_id=094d4e3a7b267f7e12d8710c69bcb7d6; xq_a_token=06c970814873215375f1cd02e4c8e64b740f6704; xqat=06c970814873215375f1cd02e4c8e64b740f6704; xq_r_token=9546eea976a2e2f78e2667bb2221518d5306c5b6; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTY3NzM3MDg0NiwiY3RtIjoxNjc1MjMxNjM5MDk1LCJjaWQiOiJkOWQwbjRBWnVwIn0.mGtkZhc8_rCJ309bA97CN-ekBtjEHmj3uy9pbKIlNQl6nBWYnSpzn8bpWkmpoKdgky3gcgTF0JZx7xxc87iBGQOW28WgtjJIS5roeXplwiFAxE9Rq8X_RKTsPTSCtfG6zX25jPZ53eNds8oRG_6jqaP8tnwOTY8kilFuy-1SDU5WxDslyPEJ3lA07qkLa7a5WRIk2ywguaQJ5Fau8Qv5Z_nojKC6g8CGocmQaN5TpFmtjxkm-pH0IBXGmji13WDPl-PY9tx2Gc_LE3MH2hXhW6kL96iY5NvamMo6g0uGX7LXvc3UO3VXCsIceLPfiyB2RUkoG4LdAv_51HBRUU_s9Q; u=451675231666753; Hm_lvt_1db88642e346389874251b5a1eded6e3=1672799041,1672884321,1673311577,1675231668; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1675231668
  xueQiuStockDetailUrl: http://stock.xueqiu.com/v5/stock/chart/kline.json?symbol={code}&begin={time}&period=day&type=before&count=-{recentDayNumber}&indicator=kline,pe,pb,ps,pcf,market_capital,agt,ggt,balance
  hangYeCodeUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112304687417704687693_1675242011928&pn=1&pz=500&po=1&np=1&fields=f12%2Cf13%2Cf14%2Cf174&fid=f174&fs=m%3A90%2Bt%3A2&ut=b2884a393a59ad64002292a3e90d46a5&_=1675242011932

  gaiLianCodeUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112304687417704687693_1675242011930&pn=1&pz=500&po=1&np=1&fields=f12%2Cf13%2Cf14%2Cf174&fid=f174&fs=m%3A90%2Bt%3A3&ut=b2884a393a59ad64002292a3e90d46a5&_=1675242011933


#  5hangYeZiJinLiuUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112303841355563199682_1675236174818&fid=f164&po=1&pz=50&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m%3A90+t%3A2&fields=f12%2Cf14%2Cf2%2Cf109%2Cf164%2Cf165%2Cf166%2Cf167%2Cf168%2Cf169%2Cf170%2Cf171%2Cf172%2Cf173%2Cf257%2Cf258%2Cf124%2Cf1%2Cf13 //f174 10周期       fid=f164 5周期
  hangYeZiJinLiuUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery11230940808857537514_1675240009620&fid={period}&po=1&pz=500&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m%3A90+t%3A2&fields=f12%2Cf14%2Cf2%2Cf160%2Cf174%2Cf175%2Cf176%2Cf177%2Cf178%2Cf179%2Cf180%2Cf181%2Cf182%2Cf183%2Cf260%2Cf261%2Cf124%2Cf1%2Cf13

#  5geGuZiJinLiuUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery11230940808857537514_1675240009620&fid=f174&po=1&pz=50&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m%3A90+t%3A2&fields=f12%2Cf14%2Cf2%2Cf160%2Cf174%2Cf175%2Cf176%2Cf177%2Cf178%2Cf179%2Cf180%2Cf181%2Cf182%2Cf183%2Cf260%2Cf261%2Cf124%2Cf1%2Cf13
  geGuZiJinLiuUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112306454061364134305_1675238376604&fid={period}&po=1&pz=5000&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=b:{hangYeCode}&fields=f12,f14,f2,f160,f174,f175,f176,f177,f178,f179,f180,f181,f182,f183,f260,f261,f124,f1,f13






industry:
  np: 1
  pn: 1
  pz: 100
  fs: m:90+t:2
  fields: f12,f14

stock:
  np: 1
  pn: 1
  pz: 500
  fs: b
  fields: f12,f14

industryKLine:
  fields1: f1,f3
  fields2: f51,f59
  klt: 103
  fqt: 1
  type: 90
  end: 20500101

stockKLineApi:
  fields1: f1,f3
  fields2: f57
  klt: 101
  fqt: 1
  end: 20500101
  lmt: 22